### PR TITLE
Change voxel spacing of df_example to validate visualization 

### PR DESCRIPTION
**Pull request by Besler**
I made the fake ct, cam1, and cam2 images have different sizes and spacings. They still render correctly. 
screen shot 2018-01-26 at 13 06 05

### CODE REVIEW

**Comment by Besler** [comment]
To run the test
```bash
pythonw sfr.py create df_example ct.nii cam1.nii cam2.nii
pythonw sfr.py visualize df_scene ct.nii cam1.nii cam2.nii --window=255 --level=127 --value=127
```

**Comment by Besler** [comment]
@PayamZandiyeh Whatcha think?

**Comment by Besler** [comment]
Now THAT'S speedy 👅 Thanks or doing that @PayamZandiyeh

**Comment by PayamZandiyeh** [comment]
@Besler I will get back to you before the sun sets today!

**Pull request merged**
